import { useState } from 'react';
import { KeyRound, Sparkles } from 'lucide-react';
import { api } from '../api';

const KEY_STORE = 'pathtrace.gemini_key';

function readKey() {
  try {
    return sessionStorage.getItem(KEY_STORE) ?? '';
  } catch {
    return '';
  }
}

export default function TutorPanel({ example }) {
  // The parent remounts this panel per moment (key={example.id}), so state starts fresh each time.
  const pathConcepts = example.paths.pointer.concepts;
  const [apiKey, setApiKey] = useState(readKey);
  const [concept, setConcept] = useState(String(pathConcepts[0]?.id ?? ''));
  const [answer, setAnswer] = useState(null);
  const [busy, setBusy] = useState(false);

  const saveKey = (value) => {
    setApiKey(value);
    try {
      sessionStorage.setItem(KEY_STORE, value);
    } catch {
      // storage unavailable; the key still works for this page view
    }
  };

  const ask = async (body) => {
    setBusy(true);
    setAnswer(null);
    try {
      setAnswer(await api.tutor(example.id, { ...body, api_key: apiKey || undefined }));
    } catch (err) {
      setAnswer({ error: err.message });
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="card flex flex-col gap-3" aria-label="Tutor">
      <div>
        <h2 className="card-title flex items-center gap-1.5"><Sparkles size={15} aria-hidden /> Ask the tutor</h2>
        <p className="card-sub">
          Explanations are generated from the model's actual numbers for this moment. Without a Gemini key the tutor
          answers from a template.
        </p>
      </div>
      <div className="flex flex-wrap gap-2">
        <button type="button" className="btn btn-primary" disabled={busy} onClick={() => ask({ kind: 'why' })}>
          Why this path?
        </button>
        <div className="flex gap-2 flex-1 min-w-[240px]">
          <select className="input" value={concept} onChange={(e) => setConcept(e.target.value)} aria-label="Concept to explain">
            {pathConcepts.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
          </select>
          <button type="button" className="btn shrink-0" disabled={busy || !concept}
            onClick={() => ask({ kind: 'concept', concept_id: Number(concept) })}>
            Explain
          </button>
        </div>
      </div>
      <details>
        <summary className="cursor-pointer muted text-xs flex items-center gap-1"><KeyRound size={12} aria-hidden /> Gemini API key (optional)</summary>
        <input className="input mt-2" type="password" autoComplete="off" placeholder="Stored in this browser tab only"
          value={apiKey} onChange={(e) => saveKey(e.target.value)} />
        <p className="muted text-xs mt-1 mb-0">Or set GEMINI_API_KEY in backend/.env. The key is sent to your local server only.</p>
      </details>
      {busy && <div className="skeleton" style={{ height: 72 }} />}
      {answer?.error && <p className="bad m-0 text-sm">{answer.error}</p>}
      {answer?.text && (
        <div className="rounded-lg p-3 text-sm" style={{ background: 'var(--surface-2)', border: '1px solid var(--border)' }}>
          <div className="whitespace-pre-line">{answer.text}</div>
          <div className="muted text-xs mt-2">{answer.source === 'template' ? 'Template answer (no Gemini key)' : `Generated by ${answer.source}`}</div>
        </div>
      )}
    </section>
  );
}
